default:
  processor:
    provider: databricks
    model: claude-3-5-sonnet-2
  accelerator:
    provider: openai / ollama
    model: gpt-4o-mini / qwen2.5
  systems:
    - name: synopsis
      type: embedded
    - name: qai
      type: http
      host: localhost:8001
