name: Deploy v1 Docs & Extensions #(/documentation and /extensions-site)

on:
  push:
    branches:
      - v1-docs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 

      - name: Install dependencies and build docs
        working-directory: ./documentation
        run:  |
          npm install
          npm run build

      - name: Install dependencies and build extensions-site
        working-directory: ./extensions-site
        run: |
          npm install
          npm run build


      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: |
            ./documentation/build 
            ./extensions-site/build:/extensions
          destination_dir: v1 # Deploy the site to the 'v1' subfolder
