# This workflow is triggered by a comment on an issue or PR with the text "/bundle-desktop".
# It bundles the Desktop App, then creates a PR comment with a link to download the app.
on:
  issue_comment:
    types: [created]
  workflow_dispatch:

# permissions needed for reacting to IssueOps commands on issues and PRs
permissions:
  pull-requests: write
  issues: write
  checks: read

name: Workflow to Bundle Desktop App

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger-on-command:
    name: Trigger on "/bundle-desktop" PR comment
    runs-on: ubuntu-latest
    steps:
      - uses: github/command@v1.3.0
        id: command
        with:
          command: "/bundle-desktop"
          reaction: "eyes"
          allowed_contexts: pull_request

  bundle-desktop:
    # Only run this if "/bundle-desktop" command is detected.
    if: ${{ steps.command.outputs.continue == 'true' }}
    uses: ./.github/workflows/bundle-desktop.yml
    secrets:
      CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
      CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

  pr-comment:
    name: PR Comment with Desktop App
    runs-on: ubuntu-latest
    needs: [ bundle-desktop ]
    permissions:
      pull-requests: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Comment on PR with download link
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.command.outputs.comment_id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Desktop App for this PR
            
            The following build is available for testing:
            
            - [📱 macOS Desktop App (arm64, signed)](https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/Goose-darwin-arm64.zip)

            After downloading, unzip the file and drag the Goose.app to your Applications folder. The app is signed and notarized for macOS.
            
            This link is provided by nightly.link and will work even if you're not logged into GitHub.
          edit-mode: replace
